version: '3'

services:
  pyspark-openjdk11-svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: pyspark-openjdk11:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"